unique_ids:
  assets:
    standard-page.html: VT34XTRQGETEA7B764RXGEGNZ4CAM7TW
    theme.css: IJ5BFIBJRID4RIA4N6YYLY375CBPN34Y
  forms:
    Form1: GC4YNUDQIEKRIH5UTCT5IAQ4PQ3BGD62
  modules: {}
  scripts: {}
  server_modules: {}
