unique_ids:
  assets:
    assets/Omega_logo_dark.png: 7U5XK7XH5AJNKOJB7CBAJGMWHS73HLYA
    assets/Omega_logo_light.png: MMIXVWF6F7LHAEIGJ6Y43VDG2TCXMF2F
    assets/modern_style.css: Q2UKCEXJKI3H6OGA6AVQRDDB5WOVORNS
    assets/style.css: JTOTK7K3XJORV7NWEPCTJGUSJGC3PW7A
    assets/three.min.js: CTSJXPAQGYKBAWJJMNMRKMFWTYLFUANE
    assets/xlsx.full.min.js: GSCSXUQSVK23DVMEUP676VNPDGYDVCGV
    src/IPSStudioV2.6.js: KQHVE6E237G5RD3I7BMJHDM4QCQ3SBDE
    src/IPSStudioV2.6_clean.js: YYKAWI3SSZ4C3Z7UCH5QTUNIQVQLPMBU
    src/antennas/AntennaPatterns.js: GHEYTL2XE3X3P7GXHMKFYZ7ODB4IFPSK
    src/antennas/AntennaPlacement.js: WWVIUJDBLBFBE3PN4Y7X23TIX5T42TIR
    src/antennas/AntennaPlacement_old.js: VBYBLHX7VH3CCWNIO4X5PM3K3D5L6NZS
    src/antennas/CSVCoverageSystem.js: YWVUBK4ZGH2MCXDHDHNUQ7NPREHQL7GU
    src/antennas/sendAntennaConfigurations.js: GTUCDUHFEC2H3GY4WJWAVGE2G4RTH6YL
    src/app.js: CMRRW6LRGYD4Z3AMOCEMSXMAIL6BNLZT
    src/index.html: 3EVNIYIU42V7EPXSDMS4ABIHOFM5BNBW
    src/io/DataExportSystem.js: HIFDS2QG4ZEUNGXQ3MZKPJWK6DSMPJG6
    src/io/ImportDXF.js: T5EBHU5I6PKJ5PLLDEFLJEO35JYMHAIA
    src/io/ProjectIO.js: CPZIMU2J2YCPYD3NJ5X6V274VE3FF6MB
    src/modern_index.html: UELYPZRGQQQFX53BQ564IH53ULRY5QEG
    src/optimization/pollOptimizationData.js: 7KEMUQPSPHMQ3LS4LLT2HI45PAYLCYKA
    src/propagation/PropagationModel25DN.js: PCBBELO327PYN3WAT5TFQMDYEZCM77BT
    src/propagation/RadioCalculations.js: DK2PUJZFUPHV6QMKF242ORFDXJFZQXNL
    src/propagation/SignalCalculations_archived.js: YVJL7YSJTQURYOAVTM2K4W3G2MDRLGXO
    src/system/ColorSystem.js: 6UKZNWRURTOM3XRENCBZRUT6XV54MOOS
    src/system/Config.js: CORJISBZMYYLHMUATTYVHAMTWATXWDGX
    src/system/GeometryUtils.js: 4I4OF2OHGYNPPJG3KWY3OFN6DKADUY2J
    src/system/NotificationSystem.js: ZGWQOVA53DQS33NXZMZEF6DNAD4DUOXH
    src/system/SystemSate.js: JRY4UWX6OOZUGVZMAGHKAWJGOXENS7ZP
    src/ui/CanvasInteraction.js: 62OMCHH2TTJBKL5LVG5O4S6OF7SYFWJ5
    src/ui/ContourRenderer.js: 33Q3OQLGIWU5RRGZLEJBQDZRI4FWGVV4
    src/ui/CoordinateSystem.js: HTHB2MMWWWY2PHITPC2Z5VNF2J3Y5XRQ
    src/ui/FloorPlaneManager.js: F643DX5AJWA56LNNDK7TOJ34FO4AJTTY
    src/ui/HeatmapEngine.js: UMPQK7UL45PB2FH57ZZSBZJW6UXS2EPI
    src/ui/ThreeJSRenderer.js: HQZZSV4OFN2UWGXRY3S4HZKDGJFGQB67
    src/ui/UIRenderers.js: 6NX4UC2DQQ6S2WSUF3ECSWER2XNNVV47
    src/ui/WallManager.js: AVGHUA4JJKJBUUTLVREV7SGERDYJNJIZ
  forms:
    Combined: GC4YNUDQIEKRIH5UTCT5IAQ4PQ3BGD62
  modules: {}
  scripts: {}
  server_modules: {}
